language: python

env:
        - TARGET_OS=centos
        - TARGET_OS=ubuntu

install: "pip install -r requirements.txt"

sudo: required

services:
        - docker

script:
        - python build.py --os $TARGET_OS
